/// Flutter icons Cusicon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Cusicon
///      fonts:
///       - asset: fonts/Cusicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Cusicon {
  Cusicon._();

  static const _kFontFam = 'Cusicon';
  static const String _kFontPkg = null;

  static const IconData business_time_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass_solid = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card_solid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marked_alt_solid = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
